import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

type Creneau = { ouverture: string; fermeture: string };
type Horaire = { jour: string; creneaux: Creneau[] };
type RestaurantSeed = {
  nom: string;
  adresse: string;
  distinction: number;
  latitude: number;
  longitude: number;
  imageUrls: string[];
  horaires: Horaire[];
};

type DishSeed = {
  restaurantName: string;
  title: string;
  caption: string;
  imageUrl: string;
  cuisine: string;
  mood: string;
  budget: string;
  prepTime: number;
  vegan: boolean;
  ingredients: string[];
  allergens: string[];
  tags: string[];
  sourceUrl?: string;
};

function slugify(input: string) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function buildSourceKey(restaurantName: string, title: string) {
  return `${slugify(restaurantName)}::${slugify(title)}`;
}

const restaurants: RestaurantSeed[] = [
  // ─── Lyon — 3 étoiles ────────────────────────────────────────
  {
    nom: 'Paul Bocuse',
    adresse: '40 Rue de la Plage, 69660 Collonges-au-Mont-d\'Or',
    distinction: 3,
    latitude: 45.9988,
    longitude: 4.8516,
    imageUrls: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
    ] satisfies Horaire[],
  },

  // ─── Lyon — 2 étoiles ────────────────────────────────────────
  {
    nom: 'Mère Brazier',
    adresse: '12 Rue Royale, 69001 Lyon',
    distinction: 2,
    latitude: 45.7679,
    longitude: 4.8338,
    imageUrls: [
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Takao Takano',
    adresse: '33 Rue du Bœuf, 69005 Lyon',
    distinction: 2,
    latitude: 45.7620,
    longitude: 4.8281,
    imageUrls: [
      'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=800',
      'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:15', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:15' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:15', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:15' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:15', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:15' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:15', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:15' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '19:30', fermeture: '21:15' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Le Neuvième Art',
    adresse: '173 Rue Cuvier, 69006 Lyon',
    distinction: 2,
    latitude: 45.7699,
    longitude: 4.8515,
    imageUrls: [
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '19:30', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },

  // ─── Lyon — 1 étoile ─────────────────────────────────────────
  {
    nom: 'Têtedoie',
    adresse: '14 Montée du Chemin Neuf, 69005 Lyon',
    distinction: 1,
    latitude: 45.7619,
    longitude: 4.8175,
    imageUrls: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Prairial',
    adresse: '11 Rue Chavanne, 69001 Lyon',
    distinction: 1,
    latitude: 45.7647,
    longitude: 4.8323,
    imageUrls: [
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:15', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:15', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:15', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:15', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Les Apothicaires',
    adresse: '23 Rue de Sèze, 69006 Lyon',
    distinction: 1,
    latitude: 45.7736,
    longitude: 4.8467,
    imageUrls: [
      'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    ],
    horaires: [
      { jour: 'MERCREDI', creneaux: [{ ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Pierre Orsi',
    adresse: '3 Place Kléber, 69006 Lyon',
    distinction: 1,
    latitude: 45.7741,
    longitude: 4.8460,
    imageUrls: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Substrat',
    adresse: '7 Rue Pleney, 69001 Lyon',
    distinction: 1,
    latitude: 45.7668,
    longitude: 4.8337,
    imageUrls: [
      'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '22:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Le Passe Temps',
    adresse: '52 Rue Pierre Corneille, 69003 Lyon',
    distinction: 1,
    latitude: 45.7553,
    longitude: 4.8484,
    imageUrls: [
      'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=800',
      'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '19:30', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },

  // ─── Beaune & alentours (Côte-d'Or) ─────────────────────────
  {
    nom: 'Maison Lameloise',
    adresse: '36 Place d\'Armes, 71150 Chagny',
    distinction: 3,
    latitude: 46.9144,
    longitude: 4.7442,
    imageUrls: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    horaires: [
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Loiseau des Vignes',
    adresse: '31 Rue Maufoux, 21200 Beaune',
    distinction: 1,
    latitude: 47.0241,
    longitude: 4.8383,
    imageUrls: [
      'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Le Bénaton',
    adresse: '25 Faubourg Bretonnière, 21200 Beaune',
    distinction: 1,
    latitude: 47.0258,
    longitude: 4.8456,
    imageUrls: [
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Le Jardin des Remparts',
    adresse: '10 Rue de l\'Hôtel-Dieu, 21200 Beaune',
    distinction: 1,
    latitude: 47.0271,
    longitude: 4.8368,
    imageUrls: [
      'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    ],
    horaires: [
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Hostellerie de Levernois',
    adresse: 'Route de Combertault, 21200 Levernois',
    distinction: 1,
    latitude: 47.0035,
    longitude: 4.8698,
    imageUrls: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Le Charlemagne',
    adresse: 'Route des Vergelesses, 21420 Pernand-Vergelesses',
    distinction: 1,
    latitude: 47.0785,
    longitude: 4.8426,
    imageUrls: [
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    ],
    horaires: [
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:00' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }] },
    ] satisfies Horaire[],
  },

  // ─── Mâcon & alentours ───────────────────────────────────────
  {
    nom: 'Georges Blanc',
    adresse: 'Place du Marché, 01540 Vonnas',
    distinction: 3,
    latitude: 46.2533,
    longitude: 4.9875,
    imageUrls: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    ],
    horaires: [
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:30', fermeture: '22:00' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'L\'Ambroisie',
    adresse: '19 Quai Jean Jaurès, 71000 Mâcon',
    distinction: 1,
    latitude: 46.3071,
    longitude: 4.8296,
    imageUrls: [
      'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800',
      'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
    ],
    horaires: [
      { jour: 'LUNDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '14:00' }, { ouverture: '19:00', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Le Poisson d\'Or',
    adresse: '2 Allée du Parc, 71850 Charnay-lès-Mâcon',
    distinction: 1,
    latitude: 46.2871,
    longitude: 4.8153,
    imageUrls: [
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
      'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=800',
    ],
    horaires: [
      { jour: 'MARDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'MERCREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:30' }] },
    ] satisfies Horaire[],
  },
  {
    nom: 'Auberge de Clochemerle',
    adresse: 'Rue Gabriel Chevallier, 01140 Vaux-en-Beaujolais',
    distinction: 1,
    latitude: 46.1843,
    longitude: 4.7631,
    imageUrls: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    ],
    horaires: [
      { jour: 'JEUDI',    creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:00' }] },
      { jour: 'VENDREDI', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:00' }] },
      { jour: 'SAMEDI',   creneaux: [{ ouverture: '12:00', fermeture: '13:30' }, { ouverture: '19:30', fermeture: '21:00' }] },
      { jour: 'DIMANCHE', creneaux: [{ ouverture: '12:00', fermeture: '13:30' }] },
    ] satisfies Horaire[],
  },
];

const dishes: DishSeed[] = [
  {
    restaurantName: 'Paul Bocuse',
    title: 'Truite de la Dombes fumée',
    caption: 'Truite locale fumée, mousse légère à l’oseille et œuf de caille.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900',
    cuisine: 'Française',
    mood: 'Tradition',
    budget: '€€€',
    prepTime: 40,
    vegan: false,
    ingredients: ['truite', 'oseille', 'œuf de caille', 'crème', 'beurre'],
    allergens: ['poisson', 'lait', 'oeuf'],
    tags: ['Fumé', 'Signature', 'Tradition'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/paul-bocuse',
  },
  {
    restaurantName: 'Paul Bocuse',
    title: 'Soupe aux truffes noires',
    caption: 'Soupe de volaille parfumée à la truffe, croutons dorés et parmesan.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 50,
    vegan: false,
    ingredients: ['volaille', 'truffe noire', 'crème', 'parmesan'],
    allergens: ['lait', 'gluten'],
    tags: ['Truffe', 'Raffiné', 'Signature'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/paul-bocuse',
  },
  {
    restaurantName: 'Mère Brazier',
    title: 'Poulet de Bresse rôti',
    caption: 'Poulet doré, purée maison et jus corsé aux herbes.',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900',
    cuisine: 'Française',
    mood: 'Comfort',
    budget: '€€€',
    prepTime: 55,
    vegan: false,
    ingredients: ['poulet', 'pommes de terre', 'beurre', 'thym'],
    allergens: ['lait'],
    tags: ['Rôti', 'Confort', 'Classique'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/mere-brazier',
  },
  {
    restaurantName: 'Takao Takano',
    title: 'Saumon mi-cuit au yuzu',
    caption: 'Filet de saumon délicat, gelée de yuzu et pousses japonaises.',
    imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=900',
    cuisine: 'Japonaise',
    mood: 'Date',
    budget: '€€€',
    prepTime: 35,
    vegan: false,
    ingredients: ['saumon', 'yuzu', 'daikon', 'soja'],
    allergens: ['poisson', 'soja'],
    tags: ['Citronné', 'Lumineux', 'Fine dining'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/takao-takano',
  },
  {
    restaurantName: 'Le Neuvième Art',
    title: 'Pigeon façon Rossini',
    caption: 'Pigeon rôti, foie gras poêlé et sauce au Porto.',
    imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 60,
    vegan: false,
    ingredients: ['pigeon', 'foie gras', 'porto', 'champignons'],
    allergens: ['lait'],
    tags: ['Rich', 'Signature', 'Élégant'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-neuvieme-art',
  },
  {
    restaurantName: 'Têtedoie',
    title: 'Oeuf en meurette',
    caption: 'Œuf poché, sauce au vin rouge, lardons et croûtons grillés.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900',
    cuisine: 'Française',
    mood: 'Tradition',
    budget: '€€',
    prepTime: 30,
    vegan: false,
    ingredients: ['oeuf', 'vin rouge', 'lardons', 'pain'],
    allergens: ['oeuf', 'gluten'],
    tags: ['Tradition', 'Rustique', 'Confort'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/tetedoie',
  },
  {
    restaurantName: 'Prairial',
    title: 'Courge rôtie et quinoa',
    caption: 'Courge d’automne rôtie, quinoa parfumé et gel d’herbes.',
    imageUrl: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=900',
    cuisine: 'Végétarienne',
    mood: 'Healthy',
    budget: '€€',
    prepTime: 40,
    vegan: true,
    ingredients: ['courge', 'quinoa', 'herbes', 'noix'],
    allergens: ['fruits à coque'],
    tags: ['Vegan', 'Léger', 'Équilibré'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/prairial',
  },
  {
    restaurantName: 'Les Apothicaires',
    title: 'Ravioles de foie gras',
    caption: 'Pâtes fines maison farcies au foie gras et bouillon parfumé.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900',
    cuisine: 'Française',
    mood: 'Date',
    budget: '€€€',
    prepTime: 45,
    vegan: false,
    ingredients: ['foie gras', 'pâte', 'bouillon', 'ciboulette'],
    allergens: ['gluten', 'lait'],
    tags: ['Raffiné', 'Potager', 'Signature'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/les-apothicaires',
  },
  {
    restaurantName: 'Pierre Orsi',
    title: 'Turbot rôti, beurre blanc',
    caption: 'Filet de turbot grillé, beurre blanc citronné et jeunes légumes.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 50,
    vegan: false,
    ingredients: ['turbot', 'beurre', 'citron', 'légumes'],
    allergens: ['lait'],
    tags: ['Noble', 'Raffiné', 'Classique'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/pierre-orsi',
  },
  {
    restaurantName: 'Substrat',
    title: 'Tofu fumé et miso crémeux',
    caption: 'Tofu grillé, purée de miso blanc et chips de shiitake.',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=900',
    cuisine: 'Asiatique',
    mood: 'Healthy',
    budget: '€€',
    prepTime: 35,
    vegan: true,
    ingredients: ['tofu', 'miso', 'shiitake', 'céleri'],
    allergens: ['soja'],
    tags: ['Vegan', 'Umami', 'Léger'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/substrat',
  },
  {
    restaurantName: 'Le Passe Temps',
    title: 'Magret de canard laqué',
    caption: 'Magret croustillant, sauce sucrée et garniture de betteraves.',
    imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=900',
    cuisine: 'Française',
    mood: 'Date',
    budget: '€€€',
    prepTime: 45,
    vegan: false,
    ingredients: ['canard', 'betterave', 'miel', 'vinaigre'],
    allergens: [],
    tags: ['Laqué', 'Fruité', 'Signature'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-passe-temps',
  },
  {
    restaurantName: 'Maison Lameloise',
    title: 'Langoustine en croûte',
    caption: 'Langoustine tiède enveloppée de pâte feuilletée et sauce crustacés.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 55,
    vegan: false,
    ingredients: ['langoustine', 'pâte feuilletée', 'crème', 'ail'],
    allergens: ['crustacés', 'gluten', 'lait'],
    tags: ['Crustacés', 'Luxe', 'Signature'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/maison-lameloise',
  },
  {
    restaurantName: 'Loiseau des Vignes',
    title: 'Cocotte de volaille aux champignons',
    caption: 'Volaille fondante, champignons sauvages et jus réduit.',
    imageUrl: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=900',
    cuisine: 'Française',
    mood: 'Comfort',
    budget: '€€',
    prepTime: 50,
    vegan: false,
    ingredients: ['poulet', 'champignons', 'crème', 'thym'],
    allergens: ['lait'],
    tags: ['Rustique', 'Confort', 'Terroir'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/loiseau-des-vignes',
  },
  {
    restaurantName: 'Le Bénaton',
    title: 'Saint-Jacques snackées',
    caption: 'Saint-Jacques dorées, émulsion de poireaux et jus citron.',
    imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=900',
    cuisine: 'Française',
    mood: 'Date',
    budget: '€€€',
    prepTime: 40,
    vegan: false,
    ingredients: ['saint-jacques', 'poireaux', 'citron', 'beurre'],
    allergens: ['crustacés', 'lait'],
    tags: ['Marine', 'Léger', 'Élégant'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-benaton',
  },
  {
    restaurantName: 'Le Jardin des Remparts',
    title: 'Carré d’agneau rôti',
    caption: 'Carré d’agneau aux herbes, polenta crémeuse et jus réduit.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900',
    cuisine: 'Française',
    mood: 'Tradition',
    budget: '€€€',
    prepTime: 55,
    vegan: false,
    ingredients: ['agneau', 'polenta', 'romarin', 'ail'],
    allergens: ['lait'],
    tags: ['Herbes', 'Confort', 'Classique'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-jardin-des-remparts',
  },
  {
    restaurantName: 'Hostellerie de Levernois',
    title: 'Risotto aux champignons',
    caption: 'Risotto crémeux, champignons sauvages et huile de noisette.',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900',
    cuisine: 'Italienne',
    mood: 'Comfort',
    budget: '€€',
    prepTime: 45,
    vegan: true,
    ingredients: ['riz Arborio', 'champignons', 'bouillon', 'noisettes'],
    allergens: ['fruits à coque'],
    tags: ['Vegan', 'Léger', 'Crémeux'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/hostellerie-de-levernois',
  },
  {
    restaurantName: 'Le Charlemagne',
    title: 'Filet de boeuf Wagyu',
    caption: 'Filet Wagyu, jus truffé et légumes de saison croquants.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 55,
    vegan: false,
    ingredients: ['boeuf', 'truffe', 'carottes', 'pommes de terre'],
    allergens: ['lait'],
    tags: ['Luxe', 'Signature', 'Riche'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-charlemagne',
  },
  {
    restaurantName: 'Georges Blanc',
    title: 'Gougères au fromage',
    caption: 'Gougères chaudes au comté et salade de mâche vinaigrée.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900',
    cuisine: 'Française',
    mood: 'Tradition',
    budget: '€€',
    prepTime: 30,
    vegan: false,
    ingredients: ['farine', 'comté', 'beurre', 'oeuf'],
    allergens: ['gluten', 'lait', 'oeuf'],
    tags: ['Apéro', 'Confort', 'Fromage'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/georges-blanc',
  },
  {
    restaurantName: 'L\'Ambroisie',
    title: 'Saumon mariné aux agrumes',
    caption: 'Saumon mi-cuit, citron vert, pamplemousse et fines herbes.',
    imageUrl: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=900',
    cuisine: 'Française',
    mood: 'Date',
    budget: '€€€',
    prepTime: 35,
    vegan: false,
    ingredients: ['saumon', 'agrume', 'aneth', 'huile d\'olive'],
    allergens: ['poisson'],
    tags: ['Frais', 'Léger', 'Signature'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/l-ambroisie',
  },
  {
    restaurantName: 'Le Poisson d\'Or',
    title: 'Bar grillé aux fines herbes',
    caption: 'Bar grillé, sauce vierge et légumes croquants.',
    imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=900',
    cuisine: 'Méditerranéenne',
    mood: 'Healthy',
    budget: '€€',
    prepTime: 40,
    vegan: false,
    ingredients: ['bar', 'tomate', 'basilic', 'citron'],
    allergens: ['poisson'],
    tags: ['Grillé', 'Fraîcheur', 'Léger'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-poisson-dor',
  },
  {
    restaurantName: 'Auberge de Clochemerle',
    title: 'Pavé de veau forestier',
    caption: 'Veau tendre, sauce aux champignons et purée de céleri.',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=900',
    cuisine: 'Française',
    mood: 'Comfort',
    budget: '€€',
    prepTime: 50,
    vegan: false,
    ingredients: ['veau', 'champignons', 'céleri', 'crème'],
    allergens: ['lait'],
    tags: ['Terroir', 'Classique', 'Confort'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/auberge-de-clochemerle',
  },
  {
    restaurantName: 'Têtedoie',
    title: 'Poulpe grillé à la provençale',
    caption: 'Poulpe tendre, tomates confites et gremolata au citron.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900',
    cuisine: 'Méditerranéenne',
    mood: 'Date',
    budget: '€€€',
    prepTime: 35,
    vegan: false,
    ingredients: ['poulpe', 'tomates', 'ail', 'citron'],
    allergens: ['mollusques'],
    tags: ['Marine', 'Coloré', 'Léger'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/tetedoie',
  },
  {
    restaurantName: 'Takao Takano',
    title: 'Tataki de boeuf et ponzu',
    caption: 'Bœuf saisi, sauce ponzu et salade croquante.',
    imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=900',
    cuisine: 'Japonaise',
    mood: 'Signature',
    budget: '€€€',
    prepTime: 30,
    vegan: false,
    ingredients: ['boeuf', 'soja', 'citron vert', 'salade'],
    allergens: ['soja'],
    tags: ['Umami', 'Frais', 'Épicé'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/takao-takano',
  },
  {
    restaurantName: 'Prairial',
    title: 'Velouté de petits pois mentholé',
    caption: 'Velouté vert frais avec croustillant de pois chiches.',
    imageUrl: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=900',
    cuisine: 'Végétarienne',
    mood: 'Healthy',
    budget: '€',
    prepTime: 25,
    vegan: true,
    ingredients: ['petits pois', 'menthe', 'pois chiches', 'huile'],
    allergens: [],
    tags: ['Vegan', 'Frais', 'Léger'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/prairial',
  },
  {
    restaurantName: 'Substrat',
    title: 'Salade de quinoa et légumes asiatiques',
    caption: 'Quinoa, edamame, avocat et vinaigrette au sésame.',
    imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=900',
    cuisine: 'Asiatique',
    mood: 'Healthy',
    budget: '€',
    prepTime: 20,
    vegan: true,
    ingredients: ['quinoa', 'edamame', 'avocat', 'sésame'],
    allergens: ['sésame'],
    tags: ['Vegan', 'Rapide', 'Frais'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/substrat',
  },
  {
    restaurantName: 'Pierre Orsi',
    title: 'Raviole de langoustine',
    caption: 'Raviole fine, bisque intense et émulsion de crustacés.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 50,
    vegan: false,
    ingredients: ['langoustine', 'pâte', 'crème', 'bisque'],
    allergens: ['gluten', 'crustacés', 'lait'],
    tags: ['Signature', 'Crustacés', 'Raffiné'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/pierre-orsi',
  },
  {
    restaurantName: 'Loiseau des Vignes',
    title: 'Foie gras en terrine',
    caption: 'Terrine fine, gelée de Sauternes et brioche toastée.',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900',
    cuisine: 'Française',
    mood: 'Date',
    budget: '€€€',
    prepTime: 35,
    vegan: false,
    ingredients: ['foie gras', 'Sauternes', 'brioche', 'épices'],
    allergens: ['gluten', 'lait'],
    tags: ['Raffiné', 'Sucré-salé', 'Apéritif'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/loiseau-des-vignes',
  },
  {
    restaurantName: 'Le Jardin des Remparts',
    title: 'Tataki de thon rouge',
    caption: 'Thon mi-cuit, vinaigrette soja et sésame toasté.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900',
    cuisine: 'Asiatique',
    mood: 'Date',
    budget: '€€€',
    prepTime: 30,
    vegan: false,
    ingredients: ['thon', 'soja', 'sésame', 'gingembre'],
    allergens: ['poisson', 'soja', 'sésame'],
    tags: ['Umami', 'Léger', 'Frais'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-jardin-des-remparts',
  },
  {
    restaurantName: 'Georges Blanc',
    title: 'Tartelette aux champignons',
    caption: 'Tartelette croustillante, crème aux herbes et champignons rôtis.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900',
    cuisine: 'Française',
    mood: 'Tradition',
    budget: '€€',
    prepTime: 35,
    vegan: false,
    ingredients: ['champignons', 'pâte', 'crème', 'thym'],
    allergens: ['gluten', 'lait'],
    tags: ['Classique', 'Confort', 'Champignons'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/georges-blanc',
  },
  {
    restaurantName: 'Maison Lameloise',
    title: 'Pigeon caramélisé au miel',
    caption: 'Pigeon tendre, légumes racines et réduction au miel.',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c4c5d09a?w=900',
    cuisine: 'Française',
    mood: 'Gastronomique',
    budget: '€€€€',
    prepTime: 50,
    vegan: false,
    ingredients: ['pigeon', 'miel', 'carottes', 'sésame'],
    allergens: ['fruits à coque'],
    tags: ['Sucré-salé', 'Riche', 'Signature'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/maison-lameloise',
  },
  {
    restaurantName: 'L\'Ambroisie',
    title: 'Salade tiède de homard',
    caption: 'Homard bleu, légumes croquants et sauce citronnée.',
    imageUrl: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=900',
    cuisine: 'Française',
    mood: 'Date',
    budget: '€€€€',
    prepTime: 45,
    vegan: false,
    ingredients: ['homard', 'citron', 'avocat', 'salade'],
    allergens: ['crustacés'],
    tags: ['Marine', 'Élégant', 'Léger'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/l-ambroisie',
  },
  {
    restaurantName: 'Le Poisson d\'Or',
    title: 'Brochette de lotte grillée',
    caption: 'Lotte en brochette, sauce verte et légumes croquants.',
    imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=900',
    cuisine: 'Méditerranéenne',
    mood: 'Signature',
    budget: '€€',
    prepTime: 35,
    vegan: false,
    ingredients: ['lotte', 'persil', 'ail', 'citron'],
    allergens: ['poisson'],
    tags: ['Grillé', 'Aromatique', 'Frais'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/le-poisson-dor',
  },
  {
    restaurantName: 'Auberge de Clochemerle',
    title: 'Ravioles de champignons',
    caption: 'Ravioles maison, crème de parmesan et éclats de noix.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900',
    cuisine: 'Française',
    mood: 'Comfort',
    budget: '€€',
    prepTime: 40,
    vegan: false,
    ingredients: ['champignons', 'pâte', 'parmesan', 'noix'],
    allergens: ['gluten', 'lait', 'fruits à coque'],
    tags: ['Confort', 'Rustique', 'Fromage'],
    sourceUrl: 'https://guide.michelin.com/fr/fr/restaurant/auberge-de-clochemerle',
  },
];

async function main() {
  console.log('Seeding restaurants...');

  await prisma.dish.deleteMany();
  await prisma.restaurantHoraire.deleteMany();
  await prisma.restaurant.deleteMany();

  const restaurantMap = new Map<string, { id: string; nom: string }>();

  for (const data of restaurants) {
    const restaurant = await prisma.restaurant.create({
      data: {
        nom: data.nom,
        adresse: data.adresse,
        distinction: data.distinction,
        latitude: data.latitude,
        longitude: data.longitude,
        imageUrls: JSON.stringify(data.imageUrls),
        horaires: {
          create: data.horaires.map((h) => ({
            jour: h.jour,
            creneaux: JSON.stringify(h.creneaux),
          })),
        },
      },
    });
    restaurantMap.set(restaurant.nom, { id: restaurant.id, nom: restaurant.nom });
    console.log(`  ✓ ${restaurant.distinction}⭐ ${restaurant.nom}`);
  }

  console.log(`\nSeeding ${dishes.length} dishes...`);
  for (const dish of dishes) {
    const restaurant = restaurantMap.get(dish.restaurantName) ?? Array.from(restaurantMap.values())[0];
    await prisma.dish.create({
      data: {
        sourceKey: buildSourceKey(dish.restaurantName, dish.title),
        restaurantId: restaurant.id,
        title: dish.title,
        caption: dish.caption,
        imageUrl: dish.imageUrl,
        cuisine: dish.cuisine,
        mood: dish.mood,
        budget: dish.budget,
        prepTime: dish.prepTime,
        vegan: dish.vegan,
        ingredients: JSON.stringify(dish.ingredients),
        allergens: JSON.stringify(dish.allergens),
        tags: JSON.stringify(dish.tags),
        sourceUrl: dish.sourceUrl ?? null,
      },
    });
  }

  console.log(`\nDone — ${restaurants.length} restaurants and ${dishes.length} dishes créés.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
